### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by chinik** [stooged/psDLC#2]
Hi, i need some help. I try to download Nier automata dlc (CUSA04480)
psDLC founds 3c3c dlc (3gb, but when i try download it only 128kb file created) and some themes. What did I do wrong?
Also i have day one content for nier. Is it possible to download it with your program? In your code i saw search goes with "?relationship=add-ons" but that content is not included there. Url of this content (on screen) goes to nier page. 
![default](https://user-images.githubusercontent.com/14177202/42941444-7dc713f4-8b65-11e8-82b7-1b905e784daa.PNG)
I know that some games have already included dlcs (gravity rush 2 for example), so i completely confused. Please help.

**Comment by stooged** [comment]
This application does not download any dlc at all
