### ISSUE TITLE
the menu dont show complete buttons with a low resolutions computer

### ISSUE THREAD

**Issue by Zefirott** [stooged/psDLC#5]
hi guys i used a netbook with windows 7 and have a resolution max that 1024x600 and only can see the button get dlcs list and other buttons dont appear and the program have a icon of fullscreen but is not active. I think is for the resolution of my computer. Thanks.

**Comment by stooged** [comment]
v12 will allow you to resize the form.

https://github.com/stooged/psDLC/releases
