### ISSUE TITLE
impossible to esc from settings

### ISSUE THREAD

**Issue by psycho91** [stooged/psDLC#6]
when enter in the settings, it's impossible to turn back into pkg list (last version 15)

**Comment by stooged** [comment]
click the close button

<img src="https://image.ibb.co/hyjiw8/22.jpg" border="0">

**Comment by stooged** [comment]
I will stretch the frame to the bottom of the form just incase the button is being hidden on lower resolutions

**Comment by stooged** [comment]
in v17 you can click the settings button and it will toggle the settings open or closed
